# Auto-generated by nixos-generate-config.
# Replace this file with the actual hardware-configuration.nix
# from your server after running `nixos-generate-config`.
_: {

  boot.loader = {
    systemd-boot.enable = true;
    efi.canTouchEfiVariables = true;
  };

  fileSystems."/" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "ext4";
  };
}
